#!/usr/bin/env bash

# Update package lists
apt update

# Install Nginx
apt install -y nginx

# Create the HTML file with "Hello World!" content
echo "Hello World!" > /var/www/html/index.html

# start server
service nginx start

# Ensure Nginx is listening on port 80
netstat -tulpn | grep nginx

# Test the server using curl
curl -I http://localhost/
