#!/usr/bin/env bash
# installs nginx and configures it on a remote server

sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
# Configure Nginx to listen on port 80
echo "server {
    listen 80;
    server_name _;
    root /var/www/html;
    index index.html;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location = / {
        return 200 'Hello World!';
    }
}" > /etc/nginx/sites-available/default

echo 'Hello World!' > /var/www/html/index.html
service nginx restart
